import { JapaneseRainPattern } from '../../../patterns/japanese-rain-pattern';
import type { PatternControlConfig } from './controls-registry';

export const controls: PatternControlConfig = {
    label: 'Japanese rain',
    pattern: JapaneseRainPattern,
    controls: [
        {
            id: 'characters',
            label: 'Characters',
            type: 'text',
            value: 'あかさたなはまやらわをんアカサタナハマヤラワヲン一二三四五六七八九十',
            category: 'pattern',
            description: 'Japanese characters to use for the rain effect. Leave empty to use random generation.',
        },
        {
            id: 'animationSpeed',
            label: 'Animation speed',
            type: 'range',
            value: 50,
            min: 0.1,
            max: 200,
            step: 0.1,
            category: 'pattern',
            description: 'Speed of the falling rain animation.',
        },
        {
            id: 'rainDensity',
            label: 'Rain density',
            type: 'range',
            value: 0.8,
            min: 0.1,
            max: 1.0,
            step: 0.05,
            category: 'pattern',
            description: 'Density of rain streams across the screen (0.1-1.0).',
        },
        {
            id: 'minDropLength',
            label: 'Min drop length',
            type: 'range',
            value: 8,
            min: 3,
            max: 15,
            step: 1,
            category: 'pattern',
            description: 'Minimum length of rain drops in characters.',
        },
        {
            id: 'maxDropLength',
            label: 'Max drop length',
            type: 'range',
            value: 25,
            min: 10,
            max: 50,
            step: 1,
            category: 'pattern',
            description: 'Maximum length of rain drops in characters.',
        },
        {
            id: 'minSpeed',
            label: 'Min falling speed',
            type: 'range',
            value: 0.5,
            min: 0.1,
            max: 2.0,
            step: 0.1,
            category: 'pattern',
            description: 'Minimum falling speed multiplier for rain drops.',
        },
        {
            id: 'maxSpeed',
            label: 'Max falling speed',
            type: 'range',
            value: 1.5,
            min: 0.5,
            max: 4.0,
            step: 0.1,
            category: 'pattern',
            description: 'Maximum falling speed multiplier for rain drops.',
        },
        {
            id: 'mutationRate',
            label: 'Character mutation rate',
            type: 'range',
            value: 0.04,
            min: 0,
            max: 0.2,
            step: 0.01,
            category: 'pattern',
            description: 'Probability of character changes per frame (0-0.2).',
        },
        {
            id: 'fadeOpacity',
            label: 'Trail fade opacity',
            type: 'range',
            value: 0.2,
            min: 0,
            max: 0.8,
            step: 0.05,
            category: 'pattern',
            description: 'Background fade opacity for trail effect (0-0.8).',
        }
    ],
};
