import type { RendererControlConfig } from './controls-registry';

export const controls: RendererControlConfig = {
    label: 'Renderer',
    controls: [{
        id: 'fontSize',
        label: 'Font size',
        type: 'number',
        value: 36,
        min: 8,
        max: 72,
        step: 1,
        category: 'renderer',
        description: 'Size of the rendered characters in pixels.',
    },
    {
        id: 'fontFamily',
        label: 'Font family',
        type: 'select',
        value: 'monospace',
        options: [
            { value: 'monospace', label: 'Monospace' },
            { value: 'Courier New', label: 'Courier New' },
            { value: 'Menlo', label: 'Menlo' },
            { value: 'Arial', label: 'Arial' },
            { value: 'Verdana', label: 'Verdana' }
        ],
        category: 'renderer',
        description: 'Font family used for rendering characters.',
    },
    {
        id: 'color',
        label: 'Text color',
        type: 'color',
        value: '#ffffff',
        category: 'renderer',
        description: 'Color of the rendered characters.',
    },
    {
        id: 'animated',
        label: 'Animated',
        type: 'checkbox',
        value: false,
        category: 'renderer',
        description: 'Enable or disable animation for the renderer.',
    },
    {
        id: 'backgroundColor',
        label: 'Background color',
        type: 'color',
        value: '#313131',
        category: 'renderer',
        description: 'Background color of the canvas.',
    },
    {
        id: 'animationSpeed',
        label: 'Animation speed',
        type: 'range',
        value: 50,
        min: 0.1,
        max: 200,
        step: 0.1,
        category: 'renderer',
        description: 'Speed of the animation.',
        visibleOn: [{ animated: true }],
    },
    {
        id: 'charSpacingX',
        label: 'Horizontal spacing',
        type: 'number',
        value: 0,
        min: 0,
        max: 100,
        step: 0.5,
        category: 'renderer',
        description: 'Horizontal spacing between characters. Use 0 for auto-calculation.',
    },
    {
        id: 'charSpacingY',
        label: 'Vertical spacing',
        type: 'number',
        value: 0,
        min: 0,
        max: 100,
        step: 0.5,
        category: 'renderer',
        description: 'Vertical spacing between characters. Use 0 for auto-calculation.',
    }],
};
